name: Tests

on:
  push:
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install and setup Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry config virtualenvs.in-project true
      - name: Run tests
        run: poetry run pytest -svv
